name: 'Slack Notification'
author: 'blake@surgio.com'
description: 'Broadcast that a build failed over slack.'
inputs:
  SLACK_WEBHOOK:
    description: 'Url to the slack webhook'
    required: true
    default: null
runs:
  using: 'node12'
  main: 'index.js'